import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './fonts.scss'
import './globals.scss'
import styles from './global.module.scss'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <div className={styles.main}>
          {children}
        </div>
        <footer className={styles.footer}>footer</footer>
      </body>
    </html>
  )
}

function Header() {
  return <div className={styles.masthed}>
    <div className={styles["masthed__inner-wrap"]}>
      <Link href="/">
        <div className={styles["home"]}>
          <Image src="/assets/images/logo32.png" alt="logo" width={32} height={32} className={styles.logo} priority></Image>
          <div>
            <p>FC VALUE</p>
            <p>FC 온라인 아이템 분석/시뮬레이터</p>
          </div>
        </div>
      </Link>
    </div>
  </div>
}